### ISSUE TITLE
Publish extension to Visual Studio Marketplace

### ISSUE THREAD

**Issue by eduardomourar** [bytecodealliance/vscode-wit#2]
We need to follow [this documentation](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) to package and publish the extension to the [Visual Studio Marketplace](https://marketplace.visualstudio.com/vscode).

- [x] Create VSTS organization for the `bytecodealliance` publisher: https://dev.azure.com/bytecodealliance/
- [x] Add token to this repository as a secret called `PAT_VSCE`
- [x] Modify [release workflow](https://github.com/bytecodealliance/vscode-wit/blob/21f75ef29f8834dc918f6f88707a3f408d1732f3/.github/workflows/release.yml#L37) to publish extension to VSCE
- [x] Perform publisher verification using the `bytecodealliance.org` domain

**Comment by Kylebrown9** [comment]
It would be great if we could get this done before the Componentize the World event next Friday.

**Comment by eduardomourar** [comment]
The extension is now being automatically published to https://marketplace.visualstudio.com/items?itemName=bytecodealliance.wit-idl on every new release.
