### ISSUE TITLE
Duplicate effort :)

### ISSUE THREAD

**Issue by badeend** [bytecodealliance/vscode-wit#21]
A couple of days ago I've created a VSCode extension for WIT at https://marketplace.visualstudio.com/items?itemName=badeend.vscode-wit  

... only to discover just now that there is already an official version... (Why is this not on VS Marketplace? 🥲 )

Anyhow, if there is any way my effort can help this one, just let me know. Or copy over whatever you like, it's MIT licensed.

**Comment by tschneidereit** [comment]
Hi Dave 👋🏻 My apologies for this! We do have the publisher all set up for the marketplace, but then I didn't publish the actual extension itself :(

It'd be fantastic if we could collaborate on merging the two extensions. I've now [published](https://marketplace.visualstudio.com/items?itemName=BytecodeAlliance.wit-idl) the extension as-is, but think we could rapidly improve on it with a merger.

I can take on that merger and open a PR here with you as co-author, or set you as the sole author with your approval. Or if you'd prefer that, obviously feel free to open a PR of your own :) And @eduardomourar please chime in if you'd prefer a different way to handle all this, too!

**Comment by badeend** [comment]
I've created a PR for merging most auxiliary features: #22 

Regarding the TextMate grammars; as far as I can see, our two implementations have been designed with different philosophies in mind. 
- `bytecodealliance/vscode-wit` has been designed with correctness in mind. But has a tendency to fail when the input is not (yet) a fully formed & valid WIT document.
- `badeend/vscode-wit` has been designed much more loosey-goosey. It's more likely to successfully highlight partial statements and incorrectly located declarations. (ie. a top-level `enum` declaration). But that's also the flipside, it will correctly highlight invalid code. Relying on the user to actually run wit-bindgen to detect those errors.

The golden path is probably somewhere in between.

Because of this, I doubt we'll be able to "just merge" them. Most likely we'd have to end up picking one as a base version, manually recreating desirable features from the other, and then throwing away that other one completely.

**Comment by eduardomourar** [comment]
I have no problem in us reaching a middle ground. I have one comment, though.

@badeend, I believe only after we have a language server (which will include WIT validation), we can simplify the textmate more and more. Keep in mind that the textmate is what is driving the syntax highlighting in GitHub so there is probably a minimum we want to keep in order to have a presentable wit file and markdown.

In regards to having other co-authors, I am perfectly fine with that as well.
